---
- name: add Zeal docs PPA
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] | int < 20
    - has_gui == true
  apt_repository:
    repo: ppa:zeal-developers/ppa
  notify: "update apt cache"
  become: yes

- name: install Zeal package
  apt:
    name: zeal
  when: has_gui == true
  become: yes

- name: add deb-src apt sources
  when: ansible_os_family == "Debian"
  replace:
    path: /etc/apt/sources.list
    regexp: '^# ?(deb-src.+)$'
    replace: '\1'
  notify: update apt cache
  become: yes

- name: force handlers for apt cache update
  meta: flush_handlers

- name: install software build deps packages
  apt:
    name: "{{ packages }}"
    state: build-dep
  vars:
    packages:
      - emacs
      - git
  become: yes

- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - checkinstall
      - colordiff
      - cppcheck
      - gnutls-bin
      - iperf3
      - ispell
      - libgccjit-11-dev  # for elisp native
      - libgif-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libtiff-dev
      - libtree-sitter-dev
      - libxpm-dev
      - python3-pip
      - python3-venv
      - shellcheck
  become: yes

- name: install gui packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - graphviz
      - xclip
      - xdotool
  when: has_gui == true
  become: yes

- name: install Ubuntu packages
  when: ansible_facts['distribution'] == "Ubuntu"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - clang-15
    - clang-format-15
    - clangd-15
  become: yes

- name: install Debian packages
  when: ansible_facts['distribution'] == "Debian"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - clang-13
    - clang-format-13
    - clangd-13
  become: yes

- name: pip upgrade
  pip:
    executable: pip3
    extra_args: "--upgrade"
    name: "{{ packages }}"
  vars:
    packages:
      - pip
      - setuptools
  become: yes

- name: install python packages
  pip:
    executable: pip3
    name: "{{ packages }}"
  vars:
    packages:
      - flake8
      - python-lsp-server
      - python-lsp-black

- name: add user to development groups
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - dialout
  become: yes

- name: create ~/src directory
  file:
    dest: "{{ ansible_user_dir }}/src"
    state: directory

- name: checkout Emacs source
  git:
    dest: "{{ ansible_user_dir }}/src/emacs"
    repo: https://github.com/emacs-mirror/emacs.git
    version: emacs-29.1
    depth: 1

- name: create emacs build script
  copy:
    dest: "{{ ansible_user_dir }}/src/emacs/clintbuild.sh"
    mode: 0755
    content: |
      #!/bin/bash
      set -euxo pipefail
      ./autogen.sh
      ./configure --prefix=$HOME/.local --with-x --with-x-toolkit=gtk3
      make prefix=$HOME/.local
      make prefix=$HOME/.local install

- name: checkout Git source
  git:
    dest: "{{ ansible_user_dir }}/src/git"
    repo: https://github.com/git/git
    version: v2.41.0
    depth: 1

- name: create git build script
  copy:
    dest: "{{ ansible_user_dir }}/src/git/clintbuild.sh"
    mode: 0755
    content: |
      #!/bin/bash
      set -euxo pipefail
      make prefix=$HOME/.local
      make prefix=$HOME/.local install
      make -C contrib/subtree prefix=$HOME/.local
      make -C contrib/subtree prefix=$HOME/.local install

- name: install global pycodestyle config
  copy:
    dest: "{{ ansible_user_dir }}/.config/pycodestyle"
    mode: 0644
    content: |
      [pycodestyle]
      max-line-length = 100

- name: make ~/.fonts directory
  file:
    state: directory
    path: "{{ ansible_user_dir }}/.fonts"
  when: has_gui == true

- name: download Adobe Source Code Pro roman font
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.otf
    dest: "{{ ansible_user_dir }}/.fonts"
  register: sourcecodepro_roman
  when: has_gui == true

- name: download Adobe Source Code Pro italic font
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.otf
    dest: "{{ ansible_user_dir }}/.fonts"
  register: sourcecodepro_italic
  when: has_gui == true

- name: update font cache
  when: sourcecodepro_roman.changed or sourcecodepro_italic.changed
  command: fc-cache -rv

- name: download NVM installer
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh
    dest: /tmp/nvm-install.sh
    mode: "0755"

- name: install NVM
  shell: /tmp/nvm-install.sh
  args:
    creates: "{{ ansible_user_dir }}/.nvm/nvm.sh"

