---
- name: add Zeal docs PPA
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] | int < 20
  apt_repository:
    repo: ppa:zeal-developers/ppa
  become: yes

- name: install software build deps packages
  apt:
    name: "{{ packages }}"
    state: build-dep
  vars:
    packages:
      - emacs
      - git
  become: yes

- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - checkinstall
      - colordiff
      - cppcheck
      - iperf3
      - python3-pip
      - python3-venv
      - shellcheck
      - xclip
      - xdotool
      - zeal
  become: yes

- name: install Ubuntu packages
  when: ansible_facts['distribution'] == "Ubuntu"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - clang-10
    - clang-format-10
  become: yes

- name: install Debian packages
  when: ansible_facts['distribution'] == "Debian"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - clang-7
    - clang-format-7
  become: yes

- name: pip upgrade
  pip:
    executable: pip3
    extra_args: "--upgrade"
    name: "{{ packages }}"
  vars:
    packages:
      - pip
      - setuptools
  become: yes

- name: install python packages
  pip:
    executable: pip3
    name: "{{ packages }}"
  vars:
    packages:
      - flake8

- name: add user to development groups
  user:
    name: "{{ lookup('env', 'USER') }}"
    append: yes
    groups:
      - dialout
  become: yes

- name: create ~/src directory
  file:
    dest: "/home/{{lookup('env', 'USER')}}/src"
    state: directory

# ./autogen.sh
# ./configure --prefix=$HOME/.local --with-x-toolkit=gtk3 --with-x
# make -j8
# make PREFIX=$HOME/.local install
- name: checkout Emacs source
  git:
    dest: "/home/{{lookup('env', 'USER')}}/src/emacs"
    repo: https://github.com/emacs-mirror/emacs.git
    version: emacs-27.2
    depth: 1

# make prefix=$HOME/.local
# make prefix=$HOME/.local install
# cd contrib/subtree
# make prefix=$HOME/.local
# make prefix=$HOME/.local install
- name: checkout Git source
  git:
    dest: "/home/{{lookup('env', 'USER')}}/src/git"
    repo: https://github.com/git/git
    version: v2.28.0
    depth: 1

- name: make ~/.fonts directory
  file:
    state: directory
    path: "/home/{{ lookup('env', 'USER') }}/.fonts"

- name: download Adobe Source Code Pro roman font
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.otf
    dest: "/home/{{ lookup('env', 'USER') }}/.fonts"
  register: sourcecodepro_roman

- name: download Adobe Source Code Pro italic font
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.otf
    dest: "/home/{{ lookup('env', 'USER') }}/.fonts"
  register: sourcecodepro_italic

- name: update font cache
  when: sourcecodepro_roman.changed or sourcecodepro_italic.changed
  command: fc-cache -rv
