---
all:
  hosts:
    cliddick-mac:
      email: cliddick@wing.com
      ansible_connection: local
      ansible_user: cliddick
    Family-MacBook:
      email: clint.liddick@gmail.com
      ansible_connection: local
      ansible_user: clint
    builder:
      email: clint.liddick@gmail.com
      ansible_user: clint
  vars:
    ansible_python_interpreter: /usr/bin/python3


