---
all:
  hosts:
    clint-dell:
      email: clint@aurora.tech
      ansible_connection: local
    P15S-PF38GS7D:
      email: clint.liddick@flyzipline.com
      ansible_connection: local
    marvin:
      email: clint.liddick@gmail.com
      ansible_connection: local
    Family-MacBook.local:
      email: clint.liddick@gmail.com
      ansible_connection: local
    builder:
      email: clint.liddick@gmail.com
  vars:
    ansible_python_interpreter: /usr/bin/python3


