---
all:
  hosts:
    clint-dell:
      email: clint@aurora.tech
    clint-laptop:
      email: clint@aurora.tech
    marvin:
      email: clint.liddick@gmail.com
  vars:
    ansible_connection: local
