---
all:
  hosts:
    Clint-Liddick-DY4K52RWN2:
      email: clint@aurora.tech
      ansible_connection: local
    clint-HM3QL13:
      email: clint@aurora.tech
      ansible_connection: local
    clint-vdesk:
      email: clint@aurora.tech
      ansible_connection: local
    marvin:
      email: clint.liddick@gmail.com
      ansible_connection: local
    Family-MacBook.local:
      email: clint.liddick@gmail.com
      ansible_connection: local
    builder:
      email: clint.liddick@gmail.com
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: clint


