---
all:
  hosts:
    clint-dell:
      email: clint@aurora.tech
      ansible_connection: local
    marvin:
      email: clint.liddick@gmail.com
      ansible_connection: local
    builder:
      email: clint.liddick@gmail.com
  vars:
    ansible_python_interpreter: /usr/bin/python3

