---
- hosts: clint-vdesk
  roles:
    - linux-headless
    - git
    - zsh
    - ripgrep
    - jujutsu
    - zellij
    - software-dev-power
  tasks:
    - name: install packages
      apt:
          name: "{{ packages }}"
      vars:
          packages:
          - atool
          - jq
          - moreutils
          - net-tools
          - nmon
          - pigz
          - python3-apt
          - python3-gpg
          - rename
          - screen
          - tmux
          - tree
          - zip
      become: yes

- hosts: Clint-Liddick-FWJQC06GH1
  roles:
    - mac-core
    - git
    - zsh
    - fonts
    - ripgrep
    - jujutsu

- hosts: Family-MacBook
  roles:
    - mac-core
    - ripgrep
    - git
    - software-dev-macosx
    - fonts
    - zsh
    - typesetting
    - photography
    - jujutsu
    - skills

- hosts: gir
  roles:
    - linux-headless
    - git
    - kitty
    - fonts
    - ripgrep
    - jujutsu
    - zsh
    - chinese
    - skills
  tasks:
    - name: install packages
      apt:
          name: "{{ packages }}"
      vars:
          packages:
          - atool
          - jq
          - moreutils
          - net-tools
          - nmon
          # - pigz
          # - python3-apt
          # - python3-gpg
          - rename
          - screen
          - tree
          - zip
      become: yes
