---
- name: create ~/src directory
  file:
    dest: "{{ ansible_user_dir }}/src"
    state: directory

- name: install build-essential packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - autoconf
      - build-essential
      - libssl-dev
      - texi2html
      - texinfo  # makeinfo
  become: yes
