---
- name: create ~/src directory
  file:
    dest: "/home/{{lookup('env', 'USER')}}/src"
    state: directory

- name: install build-essential packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - build-essential
  become: yes
