#!/bin/bash

# Mouse sensitivity
#xinput set-prop "Logitech USB Optical Mouse" "Device Accel Constant Deceleration" .8

export TERM="xterm-256color"

alias dig='dig +search'
alias sd='source devel/setup.bash'

if [ "$(hostname)" == 'flexo' ]; then
    source $HOME/dotfiles/base16-shell/base16-solarized.light.sh

    source /opt/ros/indigo/setup.bash

    export WORKON_HOME=~/.envs
    source /usr/local/bin/virtualenvwrapper.sh
fi
