#!/bin/bash

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias coinflip='if [[ $(( RANDOM % 2 )) -eq 0 ]]; then echo "heads"; else echo "tails"; fi'
alias dig='dig +search'
alias dockerclean='docker images | rg "<none>" | awk '\''{ print $3 }'\'' | xargs docker rmi'
alias dumpcore='ulimit -c unlimited'
alias e='emacsclient -nw'
alias filemanager='xfe'
alias generate_passphrase='rg -e "^[a-z]+$" /usr/share/dict/words | sort -R | head -25 | xargs -L 5 echo'
alias holdmybeer='sudo'
alias maximum_power='lscpu -p=cpu | grep "[0-9]" | parallel sudo cpufreq-set -g performance -c {}'
alias perfit='sudo perf record --call-graph dwarf'
alias present_monitor='xrandr --output HDMI-0 --right-of DP-0 --mode 1920x1080'
alias present_monitor_off='xrandr --output HDMI-0 --off'
alias dualscreen='xrandr --output DP-0 --auto --below HDMI-0 --output HDMI-0 --auto --primary'
alias rosmasterherb='export ROS_MASTER_URI=http://herb0.personalrobotics.ri.cmu.edu:11311'
alias rtags='tools/actions/generate_compile_commands_json.py && rc -J .'
alias rustup_web='curl https://sh.rustup.rs -sSf'
alias showperf='sudo perf report -g'
alias showpings='sudo tcpdump -i wlan0 icmp and icmp[icmptype]=icmp-echo'
alias switchclip='xsel -p -o | xsel -b'
alias toclip='xsel -b -o | xclip'
alias usecling='export PATH=/opt/cling/bin:$PATH'
alias weather='curl http://wttr.in/Cupertino'

# alias tags='ctags -eR --exclude="*.js" --exclude="bazel-*" --exclude=third_party --exclude=venv .'
