#!/bin/bash

alias dig='dig +search'
alias dumpcore='ulimit -c unlimited'
alias e='emacsclient -nw'
alias dual_monitor='xrandr --output DP-0 --auto --output HDMI-0 --auto --right-of DP-0'
alias ext_monitor='xrandr --output DP-0 --off --output HDMI-0 --auto'
alias ext_monitor_off='xrandr --output DP-0 --auto --output HDMI-0 --off'
alias filemanager='xfe'
alias present_monitor='xrandr --output HDMI-2 --right-of eDP-1 --mode 1920x1080'
alias present_monitor_off='xrandr --output HDMI-2 --off'
alias rosmasterherb='export ROS_MASTER_URI=http://herb0.personalrobotics.ri.cmu.edu:11311'
alias rustup_web='curl https://sh.rustup.rs -sSf'
alias sd='source devel/setup.bash'
alias showpings='sudo tcpdump -i wlan0 icmp and icmp[icmptype]=icmp-echo'
alias tags='tools/actions/generate_compile_commands_json.py'
alias rtags='tools/actions/generate_compile_commands_json.py && rc -J .'
# alias tags='ctags -eR --exclude="*.js" --exclude="bazel-*" --exclude=third_party --exclude=venv .'
alias usecling='export PATH=/opt/cling/bin:$PATH'
alias weather='curl http://wttr.in/Pittsburgh'

# Work
alias adiff='arc diff --nounit --excuse jenkins'
alias al='arc lint --severity advice'
alias bb='bazel build'
alias bdb='bazel build -c dbg'
alias bt='bazel test'
alias runoff='~/av/bazel-bin/common/framework/stack_run --logtostderr --policy ~/av/experimental/clint/configs/clint_logging.cfg --offline --config'
alias runon='~/av/bazel-bin/common/framework/stack_run --logtostderr -s --policy ~/av/experimental/clint/configs/clint_logging.cfg --config'
alias scryon='~/av/bazel-bin/visualization/scry/scry --config ~/av/config/scry_planner.cfg -p config/mkz-g2/cars/mkz-01.platform'
alias scrystack='~/av/bazel-bin/visualization/scry/scry --config ~/av/experimental/clint/configs/clint_scry.cfg --stack_host localhost'
alias scryfilm='~/av/bazel-bin/visualization/scry/scry --config ~/av/experimental/clint/configs/clint_scry_filming.cfg --offboard'
alias scrytools='~/av/bazel-bin/visualization/scry/scry --config ~/av/experimental/clint/configs/clint_scry_tools.cfg'

# Setup Debian packaging
export DEBEMAIL="clint@aurora.tech"
export DEBFULLNAME="Clinton Liddick"

alias dquilt="quilt --quiltrc=${HOME}/.quiltrc-dpkg"
complete -F _quilt_completion $_quilt_complete_opt dquilt

# added by travis gem
[ -f /home/clint/.travis/travis.sh ] && source /home/clint/.travis/travis.sh
