---
- name: install typst
  command: "{{ ansible_user_dir }}/.cargo/bin/cargo install typst-cli"
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/typst"

- name: install pandoc
  when: ansible_facts["distribution"] == "MacOSX"
  homebrew:
    name: pandoc
    state: present
