---
- name: install typst
  command: "{{ ansible_user_dir }}/.cargo/bin/cargo install typst-cli"
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/typst"

- name: install pandoc
  when: ansible_facts["distribution"] == "MacOSX"
  homebrew:
    name: pandoc
    state: present

- name: check pdflatex installation
  when: ansible_facts["distribution"] == "MacOSX"
  stat:
    path: /Library/TeX/texbin/pdflatex
  register: pdflatex_check

- name: print pdflatex installation instructions
  when: not pdflatex_check.stat.exists and ansible_facts["distribution"] == "MacOSX"
  debug:
    msg: "pdflatex not found. Use 'brew install basictex' to install"

- name: install multimarkdown
  when: ansible_facts["distribution"] == "MacOSX"
  homebrew:
    name: multimarkdown
    state: latest
