---
- name: download Digikam
  get_url:
    url: http://mirrors.ocf.berkeley.edu/kde/stable/digikam/7.1.0/digikam-7.1.0-x86-64.appimage
    checksum: "sha256:5f14cc3c1d0e9c013e5fd1c2f71b8f7a925cdc3faaa3ab1b19c3c9181e1c3db9"
    dest: "/home/{{ ansible_user }}/.local/bin/digikam-7.1.0-x86-64.appimage"
    mode: 0755

- name: symlink latest Digikam version
  file:
    state: link
    path: "/home/{{ ansible_user }}/.local/bin/digikam"
    src: "/home/{{ ansible_user }}/.local/bin/digikam-7.1.0-x86-64.appimage"

- name: add Debian backports list
  when: ansible_facts['distribution'] == "Debian"
  copy:
    dest: /etc/apt/sources.list.d/buster-backports.list
    content: |
      # Deactivated by default (pinned to 100 by "ButAutomaticUpgrades: yes" in Release
      # Use `apt-get -t buster-backports install foo`
      deb https://deb.debian.org/debian buster-backports main
  become: yes

- name: install Darktable
  apt:
    package: darktable
    default_release: buster-backports
  become: yes
