---
- name: install NAS backups mount
  file:
    path: /etc/systemd/system/mnt-nas-backups.mount
    state: absent
  become: yes

- name: install borg-backup
  get_url:
    url: "https://github.com/borgbackup/borg/releases/download/1.1.15/borg-linux64"
    checksum: "sha256:9e87a2b19a6d1034abedf3265bbf5f063238246fc56e6087b6ec4a21f29b4239"
    dest: /usr/local/bin/borg
    mode: 0755
  become: yes

- name: install backup script
  copy:
    src: backup_with_borg.sh
    dest: /usr/local/sbin/backup_with_borg
    mode: 0755
  become: yes

- name: install borg backup service
  copy:
    src: borg-backup.service
    dest: /etc/systemd/system/
    mode: 0644
  become: yes

- name: install borg backup target
  copy:
    src: borg-backup.target
    dest: /etc/systemd/system/
    mode: 0644
  become: yes

- name: install borg backup timer
  copy:
    src: borg-backup.timer
    dest: /etc/systemd/system/
    mode: 0644
  become: yes

- name: reload borg backup service files
  systemd:
    daemon_reload: yes
  become: yes

- name: enable borg backup timer
  systemd:
    name: borg-backup.timer
    enabled: yes
    state: started
  become: yes

- name: enable borg backup service
  systemd:
    name: borg-backup.service
    enabled: yes
  become: yes
