---
- name: install packages
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
  become: yes

- name: set git user.name
  git_config:
    name: user.name
    scope: global
    value: Clint Liddick

- name: set git user.email
  git_config:
    name: user.email
    scope: global
    value: "{{email}}"

- name: set git lol alias
  git_config:
    name: alias.lol
    scope: global
    value: "log --graph --abbrev-commit --all --decorate --date=format:%F --pretty=format:'%C(auto)%h %d %s - [%aN %cd]'"

- name: set git config fetch.prune true
  git_config:
    name: fetch.prune
    scope: global
    value: true

- name: set git config pull fast-forward only
  # use git pull --rebase or --no-rebase to override
  git_config:
    name: pull.ff
    scope: global
    value: only

- name: set git co alias
  git_config:
    name: alias.co
    scope: global
    value: "checkout"

- name: install mercurial config file
  ansible.builtin.copy:
    content: |
      [ui]
      username = Clint Liddick <{{ email }}>
      merge = :merge3
    dest: "{{ ansible_user_dir }}/.hgrc"
