---
- name: install packages
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
    - acpi
    - awesome
    - firefox
    - gnupg2
    - moreutils
    - nmon
    - paperkey
    - python3-apt
    - rxvt-unicode-256color
    - scrot
  become: yes

- name: create dotfile symlinks
  file:
    state: link
    src: "/home/{{ ansible_user }}/dotfiles/{{ item }}"
    path: "/home/{{ ansible_user }}/.{{ item }}"
    force: yes
  loop:
    - bash_profile
    - bashrc
    - clang-format
    - emacs.el
    - profile
    - vimrc
    - xinitrc
    - xsession

- name: create xsessionrc symlink
  file:
    state: link
    src: "/home/{{ ansible_user }}/dotfiles/xsessionrc.{{ inventory_hostname }}"
    path: "/home/{{ ansible_user }}/.xsessionrc"

- name: create Xresources symlink
  file:
    state: link
    src: "/home/{{ ansible_user }}/dotfiles/Xresources.{{ inventory_hostname }}"
    path: "/home/{{ ansible_user }}/.Xresources"

- name: create awesome config symlink
  file:
    state: link
    src: "/home/{{ ansible_user }}/dotfiles/awesome"
    path: "/home/{{ ansible_user }}/.config/awesome"

- name: check if Dropbox installed
  shell: which dropbox
  register: has_dropbox
  ignore_errors: yes

- name: install Dropbox
  when: has_dropbox.rc != 0
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
