---
- name: check if rustup installed
  shell: which rustup
  register: has_rustup
  ignore_errors: yes

- name: download rustup installer
  when: has_rustup.rc != 0
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755

- name: run rustup installer
  when: has_rustup.rc != 0
  command: /tmp/rustup.sh -y --no-modify-path --default-toolchain stable
  args:
    creates: "/home/{{ lookup('env', 'USER') }}/.cargo/bin/cargo"

# - name: check if ripgrep installed
#   shell: which rg
#   register: has_ripgrep
#   ignore_errors: yes

- name: install ripgrep
  command: "/home/{{lookup('env', 'USER')}}/.cargo/bin/cargo install ripgrep"
  args:
  # when: has_ripgrep.rc != 0
    creates: "/home/{{ lookup('env', 'USER') }}/.cargo/bin/rg"
